name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/10 * * * *"  # Run every 10 minutes
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install || yarn install --network-concurrency 1
      
    - name: Set start time
      id: start-time
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Start application
      run: |
        echo "Running application..."
        npm start &
        APP_PID=$!
        
        # Wait for 10 minutes (600 seconds)
        sleep 600

        # After 10 minutes, restart the application
        echo "Restarting application..."
        kill $APP_PID  # Stop the current instance
        sleep 5  # Allow time for cleanup
        npm start &   # Start a new instance
        echo "New instance started."
        echo "APP_PID=$!" >> $GITHUB_ENV  # Update application PID for the new instance

